version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build:
      context: ../..  # Корень вашего проекта
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../:/app  # Монтируем корень проекта в /app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_redis
    ports:
      - "8001:8000"
    depends_on:
      - redis

  worker_urgent:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/redis/wait_for_redis.sh celery -A djangoProject worker -Q high_priority -l info
    volumes:
      - ../../:/app  # Монтируем корень проекта в /app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_redis
    depends_on:
      - redis

  worker_background:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/redis/wait_for_redis.sh celery -A djangoProject worker -Q medium_priority,low_priority -l info
    volumes:
      - ../../:/app  # Монтируем корень проекта в /app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_redis
    depends_on:
      - redis
    restart: on-failure

  beat:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/redis/wait_for_redis.sh celery -A djangoProject beat -l info
    volumes:
      - ../../:/app  # Монтируем корень проекта в /app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_redis
    depends_on:
      - redis

  flower:
    build:
      context: ../..  # Корень вашего проекта
    command: celery -A djangoProject flower --port=5555
    volumes:
      - ../../:/app  # Монтируем корень проекта в /app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_redis
    ports:
      - "5555:5555"
    depends_on:
      - redis
