version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - redis

  worker_urgent:
    build: .
    command: ./wait_for_redis.sh celery -A djangoProject worker -Q urgent_tasks -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  worker_background:
    build: .
    command: ./wait_for_redis.sh celery -A djangoProject worker -Q background_tasks -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    # Эта очередь будет ожидать завершения очереди urgent_tasks
    restart: on-failure

  beat:
    build: .
    command: ./wait_for_redis.sh celery -A djangoProject beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A djangoProject flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
