version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15673:15672"

  web:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/rabbitmq/wait_for_rabbitmq.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_rabbitmq
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  worker_urgent:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/rabbitmq/wait_for_rabbitmq.sh celery --app=djangoProject worker --queues=high_priority --loglevel=info
    volumes:
      - ../../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_rabbitmq
    depends_on:
      - rabbitmq

  worker_background:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/rabbitmq/wait_for_rabbitmq.sh celery --app=djangoProject worker --queues=medium_priority, low_priority --loglevel=info
    volumes:
      - ../../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_rabbitmq
    depends_on:
      - rabbitmq

  beat:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/rabbitmq/wait_for_rabbitmq.sh celery --app=djangoProject beat --loglevel=info
    volumes:
      - ../../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_rabbitmq
    depends_on:
      - rabbitmq

  flower:
    build:
      context: ../..  # Корень вашего проекта
    command: ./docker/rabbitmq/wait_for_rabbitmq.sh celery --app=djangoProject flower --port=5555
    volumes:
      - ../../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=djangoProject.settings_rabbitmq
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
